---

sites:
  - page_identifier: landing_generator
    title: Landing Generator
    tagline: Generate landing pages with email collection in minutes.
    description: Generate landing pages with email collection in minutes.
    item_1_title: Validate your idea
    item_1_description: Create a landing page to validate your idea.
    item_2_title: Collect emails
    item_2_description: You will have an audience ready for when you launch.
    item_3_title: Self hosted
    item_3_description: Host your landing page on your own server.
    item_4_title: Secure
    item_4_description: Your data is safe and secure and not shared with anyone.
    button_text: Get more info
